const data = {
  about: {
    categories: [
      "bolsas",
      "chamarras",
      "faldas",
      "pantalones",
      "playeras-y-tops",
      "chicos"
    ]
  },
  items: [
    { "id": "1",  "image": "/products/tote9a.jpg",                                               "name": "corazoncito",           "category": "bolsas",          "price": "$280"  },
    { "id": "2",  "image": "/products/WhatsAppImage2025-05-05at8.51.04PM_1.jpg",                 "name": "serendipia",            "category": "bolsas",          "price": "$280"  },
    { "id": "3",  "image": "/products/DSC08499.webp",                                            "name": "bodoque",               "category": "chamarras",       "price": "$1120" },
    { "id": "4",  "image": "/products/DSC08450.webp",                                            "name": "chocotorro",            "category": "chamarras",       "price": "$880"  },
    { "id": "5",  "image": "/products/Sin_titulo-1.webp",                                        "name": "cyan",                  "category": "chamarras",       "price": "$600"  },
    { "id": "6",  "image": "/products/WhatsAppImage2024-10-22at4.50.00PM_2 (1).webp",            "name": "cyan mezclilla",        "category": "chamarras",       "price": "$580"  },
    { "id": "7",  "image": "/products/DSC08399_e478e1c6-0c9e-4b76-8048-9ee572f8c37c.webp",      "name": "dalmata",               "category": "chamarras",       "price": "$880"  },
    { "id": "8",  "image": "/products/DSC08343_c4a6b808-7fc5-47e9-8c86-0a3a96661c68.webp",      "name": "nube",                  "category": "chamarras",       "price": "$780"  },
    { "id": "9",  "image": "/products/DSC08364_77d2e73d-4b83-42f1-8f32-0fb9207b5128.webp",      "name": "rebozo",                "category": "chamarras",       "price": "$980"  },
    { "id": "10", "image": "/products/WhatsAppImage2024-12-30at5.09.51PM.webp",                  "name": "susuwatari",            "category": "chamarras",       "price": "$600"  },
    { "id": "11", "image": "/products/WhatsAppImage2024-12-30at4.01.28PM_1.webp",                "name": "amapola",               "category": "faldas",          "price": "$620"  },
    { "id": "12", "image": "/products/DSC05946.webp",                                            "name": "azulina",               "category": "faldas",          "price": "$480"  },
    { "id": "13", "image": "/products/WhatsAppImage2025-01-26at8.47.44PM_3.webp",               "name": "brillantina",           "category": "faldas",          "price": "$420"  },
    { "id": "14", "image": "/products/DSC08191.webp",                                            "name": "copo de nieve",         "category": "faldas",          "price": "$920"  },
    { "id": "15", "image": "/products/satin2.webp",                                              "name": "davy",                  "category": "faldas",          "price": "$400"  },
    { "id": "16", "image": "/products/WhatsAppImage2024-09-04at2.43.36PM.webp",                  "name": "mantel",                "category": "faldas",          "price": "$640"  },
    { "id": "17", "image": "/products/DSC05903.webp",                                            "name": "marina",                "category": "faldas",          "price": "$480"  },
    { "id": "18", "image": "/products/xiimm.webp",                                               "name": "medusa",                "category": "faldas",          "price": "$510"  },
    { "id": "19", "image": "/products/DSC00242.webp",                                            "name": "piano",                 "category": "faldas",          "price": "$890"  },
    { "id": "20", "image": "/products/DSC08011.webp",                                            "name": "pintura",               "category": "faldas",          "price": "$580"  },
    { "id": "21", "image": "/products/DSC05959.webp",                                            "name": "rojita",                "category": "faldas",          "price": "$480"  },
    { "id": "22", "image": "/products/DSC05907.webp",                                            "name": "rosetta",               "category": "faldas",          "price": "$480"  },
    { "id": "23", "image": "/products/WhatsAppImage2024-11-09at6.16.14PM.webp",                  "name": "té negro",              "category": "faldas",          "price": "$580"  },
    { "id": "24", "image": "/products/DSC08229.webp",                                            "name": "uva sin semilla",       "category": "faldas",          "price": "$880"  },
    { "id": "25", "image": "/products/DSC07897.webp",                                            "name": "vidia",                 "category": "faldas",          "price": "$480"  },
    { "id": "26", "image": "/products/WhatsAppImage2025-05-05at8.43.38PM_3.webp",               "name": "botones",               "category": "pantalones",      "price": "$880"  },
    { "id": "27", "image": "/products/WhatsAppImage2025-06-29at10.01.09PM.webp",                 "name": "cassita en mi corazón", "category": "pantalones",      "price": "$980"  },
    { "id": "28", "image": "/products/WhatsAppImage2024-09-05at12.03.50PM_1.webp",               "name": "insectos",              "category": "pantalones",      "price": "$2200" },
    { "id": "29", "image": "/products/WhatsApp_Image_2025-06-29_at_10.21.10_PM.webp",            "name": "sin cassita",           "category": "pantalones",      "price": "$820"  },
    { "id": "30", "image": "/products/DSC00167.webp",                                            "name": "té lavanda",            "category": "pantalones",      "price": "$560"  },
    { "id": "31", "image": "/products/DSC00155.webp",                                            "name": "té limón",              "category": "pantalones",      "price": "$560"  },
    { "id": "32", "image": "/products/DSC08476.webp",                                            "name": "té verde",              "category": "pantalones",      "price": "$560"  },
    { "id": "33", "image": "/products/4BB555BD-9A52-43F1-8B10-0C46D9890A57.webp",               "name": "acrobacia",             "category": "playeras-y-tops", "price": "$480"  },
    { "id": "34", "image": "/products/WhatsApp_Image_2025-04-09_at_12.15.40_PM.jpg",            "name": "amor mío",              "category": "playeras-y-tops", "price": "$510"  },
    { "id": "35", "image": "/products/DSC08378.webp",                                            "name": "colores",               "category": "playeras-y-tops", "price": "$580"  },
    { "id": "36", "image": "/products/WhatsAppImage2025-01-04at10.06.53PM_1.webp",               "name": "diario",                "category": "playeras-y-tops", "price": "$230"  },
    { "id": "37", "image": "/products/697447F6-BA56-4499-93BF-781FE6C5964C.webp",               "name": "dulce",                 "category": "playeras-y-tops", "price": "$480"  },
    { "id": "38", "image": "/products/WhatsAppImage2025-05-05at9.09.26PM.webp",                  "name": "efímero",               "category": "playeras-y-tops", "price": "$360"  },
    { "id": "39", "image": "/products/DSC08275.webp",                                            "name": "horchata",              "category": "playeras-y-tops", "price": "$530"  },
    { "id": "40", "image": "/products/1E237D20-F507-478C-A9EA-6D1417E0AA8A.webp",               "name": "lazo",                  "category": "playeras-y-tops", "price": "$420"  },
    { "id": "41", "image": "/products/DSC08301_31126b93-8565-4f1b-84d9-13a3b7ee5b82.webp",      "name": "liviano",               "category": "playeras-y-tops", "price": "$580"  },
    { "id": "42", "image": "/products/WhatsAppImage2025-05-05at9.09.36PM_1.webp",               "name": "lunarcitos",            "category": "playeras-y-tops", "price": "$420"  },
    { "id": "43", "image": "/products/DSC07989.webp",                                            "name": "malteada",              "category": "playeras-y-tops", "price": "$700"  },
    { "id": "44", "image": "/products/DSC08018.webp",                                            "name": "mar",                   "category": "playeras-y-tops", "price": "$480"  },
    { "id": "45", "image": "/products/mermelada.webp",                                           "name": "mermelada",             "category": "playeras-y-tops", "price": "$710"  },
    { "id": "46", "image": "/products/90EF5C23-983F-4B36-BC97-F2B8951730CC.webp",               "name": "palomita",              "category": "playeras-y-tops", "price": "$420"  },
    { "id": "47", "image": "/products/WhatsApp_Image_2025-05-05_at_9.09.22_PM.webp",            "name": "pastel",                "category": "playeras-y-tops", "price": "$320"  },
    { "id": "48", "image": "/products/8480A23E-F633-47BD-B194-3C14A209A8F8.webp",               "name": "pirata",                "category": "playeras-y-tops", "price": "$420"  },
    { "id": "49", "image": "/products/488B33D4-71A5-4144-A3FA-73C43F5EEB25.webp",               "name": "romance",               "category": "playeras-y-tops", "price": "$420"  },
    { "id": "50", "image": "/products/D5090617-DB5E-4ADC-8B88-8F8DDABE1D0A.webp",               "name": "suspiros",              "category": "faldas", "price": "$620"  },
    { "id": "51", "image": "/products/WhatsAppImage2025-06-29at10.01.07PM.webp",                 "name": "tartaleta",             "category": "playeras-y-tops", "price": "$480"  },
    { "id": "52", "image": "/products/7CE2957B-7C4A-41C0-97DB-08D23F5D44E9.webp",               "name": "trapecista",            "category": "playeras-y-tops", "price": "$480"  },
    { "id": "53", "image": "/products/9CB5CEAF-41BA-45CE-994C-B56C6382DE11.webp",               "name": "valentina",             "category": "playeras-y-tops", "price": "$880"  },
    { "id": "54", "image": "/products/222.webp",                                                 "name": "camisa mermelada",      "category": "chicos",          "price": "$480"  }
  ]
};

module.exports = data;
