// Maps product slug → Stripe buy-button-id.
// To add a product: create a Payment Link in the Stripe dashboard,
// then copy the buy-button-id shown in the "Buy button" embed code and add it here.
export const STRIPE_BUY_BUTTONS: Record<string, string> = {
  serendipia: "buy_btn_1TTPsXBccquMyXX4IbOp88Qn",
  "corazoncito": "buy_btn_1TTlGeBccquMyXX4SsOmVa1Z",
  "bodoque": "buy_btn_1TTlOaBccquMyXX4NHPsYtkm",
  "chocotorro":"buy_btn_1TTlQjBccquMyXX4zcpGDqCE",
  "cyan":"buy_btn_1TTlSVBccquMyXX4hJoLhEtB",
  "cyan-mezclilla":"buy_btn_1TTlTzBccquMyXX45K00pExD",
  "dalmata":"buy_btn_1TTmwABccquMyXX4UEfLmQMn",
  "nube":"buy_btn_1TTmxvBccquMyXX4RxbABBq8",
  "rebozo":"buy_btn_1TTmzcBccquMyXX4KbL5Rn37",
  "susuwatari":"buy_btn_1TTn1XBccquMyXX47g5cix8p",
  "camisa-mermelada":"buy_btn_1TTnEnBccquMyXX4mqlPU5dy",
  "cassita-en-mi-corazon":"buy_btn_1TTnI6BccquMyXX4LUp378Rs",
  "sin-cassita":"buy_btn_1TTnKpBccquMyXX4xN8U16jN",
  "amapola":"buy_btn_1TTnQBBccquMyXX4Ga5PyzK0",
  "azulina":"buy_btn_1TTnRbBccquMyXX45lB6LXM6",
  "brillantina":"buy_btn_1TTnTLBccquMyXX4tgwdtnbL",
  "copo-de-nieve":"buy_btn_1TTnhpBccquMyXX4b5WEXxte",
  "davy":"buy_btn_1TTnmqBccquMyXX4gZXZV9Za",
  "marina":"buy_btn_1TTo8PBccquMyXX4tiK1vICv",
  "medusa":"buy_btn_1TToGEBccquMyXX42XzBlihv",
  "piano":"buy_btn_1TToHoBccquMyXX40e6qbp5a",
  "pintura":"buy_btn_1TToJkBccquMyXX48jQqsNoo",
  "rojita":"buy_btn_1TToMzBccquMyXX4mohhTJFS",
  "rosseta":"buy_btn_1TToONBccquMyXX4VGNodzdo",
  "té-negro":"buy_btn_1TToPyBccquMyXX43ynMamNE",
  "uva-sin-semilla":"buy_btn_1TTorEBccquMyXX4EmENWnPM",
  "vidia":"buy_btn_1TTp5JBccquMyXX4rIhbIDep",
  "botones":"buy_btn_1TTpcqBccquMyXX4NTwoONqr",
  "insectos":"buy_btn_1TTpeDBccquMyXX4rJA03cqo",
  "te-lavanda":"buy_btn_1TTpffBccquMyXX4Nb4xwanO",
  "te-limon":"buy_btn_1TTph9BccquMyXX47Gf78a5P",
  "te-verde":"buy_btn_1TTpizBccquMyXX4LFUabiCT",
  "valentina":"buy_btn_1TTpl9BccquMyXX4NDPTNZnv",
  "trapecista":"buy_btn_1TTpn5BccquMyXX4RWUve345",
  "tartaleta":"buy_btn_1TTponBccquMyXX47B3zxhx6",
  "suspiros":"buy_btn_1TTpqpBccquMyXX4LAwb17Ux",
  "romance":"buy_btn_1TTpzaBccquMyXX4injqhNm8",
  "acrobacia":"buy_btn_1TTq2EBccquMyXX4Z6uT5EOd",
  "amor-mio":"buy_btn_1TTq3kBccquMyXX4wFI6FnTw",
  "colores":"buy_btn_1TTq5OBccquMyXX44eOmnKOp",
  "diario":"buy_btn_1TTqPkBccquMyXX4vsemFSnP",
  "dulce":"buy_btn_1TTqRmBccquMyXX4q7bvZisX",
  "efímero":"buy_btn_1TTqTiBccquMyXX4abBBmjAD",
  "horchata":"buy_btn_1TTqVIBccquMyXX4ruCc1Eqa",
  "lazo":"buy_btn_1TTqX7BccquMyXX4ZhcrpAkI",
  "liviano":"buy_btn_1TTqZDBccquMyXX46Z2KcuVH",
  "lunarcitos":"buy_btn_1TTqbPBccquMyXX42fJ5M0J8",
  "malteada":"buy_btn_1TTqeWBccquMyXX44zf1teQd",
  "mar":"buy_btn_1TTqmjBccquMyXX4rxZG0mko",
  "mermelada":"buy_btn_1TTqorBccquMyXX4cclaeYNm",
  "palomita":"buy_btn_1TTqqiBccquMyXX4rTzA7Bjw",
  "pastel":"buy_btn_1TTqstBccquMyXX4LIjJoElO",
  "pirata":"buy_btn_1TTquvBccquMyXX4Vc6aYJSy"
};

export const STRIPE_PUBLISHABLE_KEY =
  "pk_test_51TRkMfBccquMyXX4D6EWp3JxSxSzqqCnrAZCEgGCq1sgjd3at7hiFpqv75NLT0Va2gVmr1VAU8qFaJKr2UKUE3vD00KueLE1Vj";
